tournament:
  basketball:
  - team: Gettin' Wiggy With It.
    players: Tomson, Gary, Peter
  - team: Better Call Gasol.
    players: Sam, Gasol, Lila
  - team: Adam's Family.
    players: Morticia, Wednesday, Gomez
  - team: Locker Room Talk.
    players: Sara, Leticia, Josh
  - team: Skyhookers.
    players: Samuel, Seth, Antonia